name: Master

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

jobs:
  deploy-server:
    name: Deploy Server with CloudFormation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: server-stack
          template: ./server/cloudformation.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "Environment=production"